#!/bin/bash

# Quick Setup Instructions for Onchainweb Platform
# ================================================

echo "🎯 ONCHAINWEB SETUP CHECKLIST"
echo "=============================="
echo ""
echo "✅ Step 1: Dependencies installed"
echo "✅ Step 2: Environment file created"
echo ""
echo "⚠️  Step 3: SUPABASE SETUP REQUIRED"
echo ""
echo "You need to set up Supabase (takes 5 minutes):"
echo ""
echo "1. Go to: https://supabase.com"
echo "2. Click 'Start your project' (sign up with GitHub)"
echo "3. Click 'New Project'"
echo "4. Fill in:"
echo "   - Name: onchainweb"
echo "   - Database Password: (save this securely!)"
echo "   - Region: Choose closest to you"
echo "5. Wait ~2 minutes for project to initialize"
echo ""
echo "6. Once ready, go to SQL Editor (left sidebar)"
echo "7. Click 'New Query'"
echo "8. Copy entire contents of: server/database/schema.sql"
echo "9. Paste and click 'Run'"
echo "10. You should see '✓ Success. No rows returned'"
echo ""
echo "11. Go to Settings → API (left sidebar)"
echo "12. Copy these 3 values:"
echo "    - Project URL"
echo "    - anon public key"
echo "    - service_role secret key"
echo ""
echo "13. Run: ./configure-env.sh"
echo "    (I'll help you paste the values)"
echo ""
echo "After Supabase setup, I'll start the servers automatically!"
echo ""
echo "📚 Need help? Check server/README.md"
echo ""
